/* eslint-disable @next/next/no-img-element */
// This route renders an off-DOM image via Satori; next/image does not apply here.
import { ImageResponse } from "next/og";
import { readFileSync } from "node:fs";
import { join } from "node:path";

export const runtime = "nodejs";

const assets = (f) => join(process.cwd(), "lib/og-assets", f);

const fontRegular = readFileSync(assets("Inter-400.woff"));
const fontBold = readFileSync(assets("Inter-700.woff"));

// path -> { title, description, eyebrow }; generated by scripts/gen-og-manifest.mjs.
const manifest = JSON.parse(
  readFileSync(join(process.cwd(), "lib/og-manifest.json"), "utf8"),
);

const SIZE = { width: 1200, height: 630 };

export async function GET(request) {
  const { searchParams } = new URL(request.url);

  // Cards are referenced by path only. Anything not in the manifest is rejected
  // so the endpoint can't be used to render arbitrary text on the brand card.
  const path = searchParams.get("path");
  const entry = path ? manifest[path] : null;
  if (!entry) {
    return new Response("Not found", { status: 404 });
  }
  const title = entry.title.slice(0, 100);
  const description = (entry.description || "").slice(0, 200);
  const eyebrow = (entry.eyebrow || "").slice(0, 40);

  return new ImageResponse(
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-end",
        fontFamily: "Inter",
        color: "#F4F6FB",
        backgroundColor: "#17151D",
        padding: "72px",
        position: "relative",
      }}
    >
      <div
        style={{
          display: "flex",
          position: "absolute",
          top: 60,
          right: 72,
          alignItems: "center",
          gap: 18,
        }}
      >
        <div
          style={{
            display: "flex",
            width: 74,
            height: 74,
            borderRadius: 18,
            border: "2px solid #5E6678",
            backgroundColor: "#211E29",
            alignItems: "center",
            justifyContent: "center",
            color: "#92D3B5",
            fontSize: 30,
            fontWeight: 700,
          }}
        >
          gr
        </div>
        <div
          style={{
            display: "flex",
            color: "#F4F2F7",
            fontSize: 44,
            fontWeight: 700,
          }}
        >
          Goalrail
        </div>
      </div>

      {/* divider above the content block */}
      <div
        style={{
          display: "flex",
          width: "100%",
          height: 1,
          backgroundColor: "#3A3446",
          marginBottom: 36,
        }}
      />

      {eyebrow ? (
        <div
          style={{
            display: "flex",
            fontSize: 24,
            fontWeight: 700,
            letterSpacing: 0,
            textTransform: "uppercase",
            color: "#92D3B5",
            marginBottom: 18,
          }}
        >
          {eyebrow}
        </div>
      ) : null}

      <div
        style={{
          display: "flex",
          fontSize: 76,
          fontWeight: 700,
          lineHeight: 1.05,
          letterSpacing: 0,
          maxWidth: 1000,
          color: "#FFFFFF",
        }}
      >
        {title}
      </div>

      {description ? (
        <div
          style={{
            display: "flex",
            fontSize: 30,
            fontWeight: 400,
            lineHeight: 1.35,
            color: "#B9B3C5",
            marginTop: 24,
            maxWidth: 940,
          }}
        >
          {description}
        </div>
      ) : null}
    </div>,
    {
      ...SIZE,
      fonts: [
        { name: "Inter", data: fontRegular, weight: 400, style: "normal" },
        { name: "Inter", data: fontBold, weight: 700, style: "normal" },
      ],
      // ImageResponse defaults to `Cache-Control: public, immutable,
      // max-age=31536000` in production, so Vercel's CDN renders each unique
      // card (title/desc/eyebrow) once and serves every later scrape from the
      // edge cache — no per-request regeneration.
    },
  );
}
